# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3668ecec36ef9de04a360708a26420e9fa1bb31872db076469f059cff5c09984cd314a7e35f931bd9fbb4924fefc85e1ae01ad0b868775b3049b6b4a77b03326

test:
  secret_key_base: 3a0bf12ed3e8b14678b822a2910d2d32cf64b9ddb2bd2b800f26708575a5e34f6bd3308e2292fbcdd06262a85ed2070c53ebc7c1abd1442ecd97e8db6db45b4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
